name: Android CI - Multi

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1-5'

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    #environment: production
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    - name: Build with Gradle init
      run: ./gradlew init
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build debug APK
      run: ./gradlew clean assembleDebug --stacktrace

    - name: Slack - Upload APK
      uses: MeilCli/slack-upload-file@v1.0.0
      with:
        slack_token: ${{ secrets.SLACK_TOKEN }}
        channels: ${{ secrets.SLACK_CHANNEL }}
        initial_comment: 'APK File Upload'
        file_type: 'apk'
        file_name: 'presentaion-debug.apk'
        file_path: './presentaion/build/outputs/apk/debug/presentaion-debug.apk'

    - name: Github - Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: apk-artifact
        path: ./presentaion/build/outputs/apk/debug/presentaion-debug.apk

  slack-success-msg:
    name: Send Build Success Msg to Slack
    needs: build
    if: needs.build.result == 'success'
    runs-on: ubuntu-latest
    steps:
    - name: Slack - Send Success Msg
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: workflow,job,commit,repo,author
        author_name: Heeg
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  slack-failure-msg:
    name: Send Build failure Msg to Slack
    needs: build
    if: needs.build.result == 'failure'
    runs-on: ubuntu-latest
    steps:
      - name: Slack - Send Fail Msg
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: workflow,job,commit,repo,author,took,ref
          author_name: Heeg
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  test_call:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Test Call
        run: echo 'Test Call'

  fin_call:
    name: Final call Job
    needs: [test_call, slack-success-msg]
    runs-on: ubuntu-latest
    steps:
      - name: Final Call
        run: echo 'Final Call'

  test_failure_call:
    name: Test Failure Job
    runs-on: ubuntu-latest
    steps:
      - name: Failure Event
        id: fail-event
        run: |
          exit 1

  fin_failure_call:
    name: Failure call Job
    needs: test_failure_call
    if: always() && needs.test_failure_call.result == 'failure'
    runs-on: ubuntu-latest
    steps:
      - name: Final Call
        run: echo 'Final Call'