name: Android CI - Email

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    - name: Build with Gradle init
      run: ./gradlew init
    - name: Build with Gradle
      run: ./gradlew build
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        subject: Github Actions Custom job result
        to: heegyeong.you@gmail.com
        from: HeeGyeong@github # <user@example.com>
        secure: true
        body: Build job of ${{github.repository}} completed successfully!
        ignore_cert: true
        convert_markdown: true
        priority: high
