name: Android CI - SLACK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  send_slack:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Slack - Send Msg
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: workflow,job,commit,repo,author
        author_name: Heeg

      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()

    - name: Slack - Upload AOK
       uses: adrey/slack-file-upload-action@master
       with:
        token: ${{ secrets.SLACK_TOKEN }}
        channel: random
        initial_comment: APK File Upload
        title: Custom Title
        filetype: 'xml'
        filename: 'AndroidManifest.xml'
        path: ./presentaion/src/main/AndroidManifrest.xml
